/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.turtle;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TurtleStandaloneSetup extends TurtleStandaloneSetupGenerated {

	public static void doSetup() {
		new TurtleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
