/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.greetings.generator;

import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.example.greetings.greetings.Element;
import org.xtext.example.greetings.greetings.Greeting;
import org.xtext.example.greetings.greetings.Model;
import org.xtext.example.greetings.greetings.Repetition;
import org.xtext.example.greetings.greetings.Subject;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class GreetingsGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    String _lastSegment = resource.getURI().lastSegment();
    String _plus = (_lastSegment + ".txt");
    fsa.generateFile(_plus, this.generatePseudoCode(IterableExtensions.<EObject>head(resource.getContents())));
  }

  protected String _generatePseudoCode(final Model m) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("BEGIN");
    _builder.newLine();
    {
      EList<Element> _elems = m.getElems();
      for(final Element g : _elems) {
        String _generatePseudoCode = this.generatePseudoCode(g);
        _builder.append(_generatePseudoCode);
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("END");
    return _builder.toString();
  }

  protected String _generatePseudoCode(final Greeting g) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("SAY \"");
    String _literal = g.getForm().getLiteral();
    _builder.append(_literal);
    _builder.append(" ");
    {
      EList<Subject> _subjects = g.getSubjects();
      for(final Subject s : _subjects) {
        String _name = s.getName();
        _builder.append(_name);
        _builder.append(" ");
      }
    }
    _builder.append("!\"");
    return _builder.toString();
  }

  protected String _generatePseudoCode(final Repetition r) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("REPEAT ");
    int _times = r.getTimes();
    _builder.append(_times);
    _builder.append(" TIMES");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("BEGIN ");
    _builder.newLine();
    {
      EList<Element> _elems = r.getElems();
      for(final Element e : _elems) {
        _builder.append("\t");
        String _generatePseudoCode = this.generatePseudoCode(e);
        _builder.append(_generatePseudoCode, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.append("END");
    return _builder.toString();
  }

  @XbaseGenerated
  public String generatePseudoCode(final EObject g) {
    if (g instanceof Greeting) {
      return _generatePseudoCode((Greeting)g);
    } else if (g instanceof Repetition) {
      return _generatePseudoCode((Repetition)g);
    } else if (g instanceof Model) {
      return _generatePseudoCode((Model)g);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(g).toString());
    }
  }
}
