/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.greetings;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GreetingsStandaloneSetup extends GreetingsStandaloneSetupGenerated {

	public static void doSetup() {
		new GreetingsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
