/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.greetings.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GreetingsUiModule extends AbstractGreetingsUiModule {

	public GreetingsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
