/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.greetings.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.greetings.greetings.Model

@ExtendWith(InjectionExtension)
@InjectWith(GreetingsInjectorProvider)
class GreetingsParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void parseHello() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}@Test
	def void parseHelloMany() {
		val result = parseHelper.parse('''
			Hello Xtext and Xtend!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
		@Test
	def void parseSalut() {
		val result = parseHelper.parse('''
			Salut Xtext!
			Salut Tom!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

		@Test
	def void parseGutenTag() {
		val result = parseHelper.parse('''
			Salut Xtext!
			Guten Tag    Tom!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
