/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.hellodsl.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.xtext.example.hellodsl.helloDsl.Greeting
import org.xtext.example.hellodsl.helloDsl.Model

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class HelloDslGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		fsa.generateFile('pseudoCode.txt', generatePseudoCode(resource.contents.head))
	}
	
	dispatch def String generatePseudoCode(Model m) 
	'''BEGIN
	«FOR g : m.greetings»
«generatePseudoCode(g)»
	«ENDFOR»
END'''
		
	dispatch def String generatePseudoCode(Greeting g) 
	'''SAY "Hello «g.subject»!"'''
}
