/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.hellodsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.hellodsl.HelloDslRuntimeModule;
import org.xtext.example.hellodsl.HelloDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HelloDslIdeSetup extends HelloDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HelloDslRuntimeModule(), new HelloDslIdeModule()));
	}
	
}
