/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.hellodsl.ide;


/**
 * Use this class to register ide components.
 */
public class HelloDslIdeModule extends AbstractHelloDslIdeModule {
}
