/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.hellodsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HelloDslUiModule extends AbstractHelloDslUiModule {

	public HelloDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
