/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.greetings.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.xtext.example.greetings.greetings.Model
import org.xtext.example.greetings.greetings.Greeting
import org.xtext.example.greetings.greetings.Repetition

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class GreetingsGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		fsa.generateFile(resource.URI.lastSegment + '.txt', generatePseudoCode(resource.contents.head))
	}
	
	dispatch def String generatePseudoCode(Model m) 
	'''BEGIN
	«FOR g : m.elems»
«generatePseudoCode(g)»
	«ENDFOR»
END'''
		
	dispatch def String generatePseudoCode(Greeting g) 
	'''SAY "«g.form.literal» «FOR s: g.subjects»«s.name» «ENDFOR»!"'''
	
		dispatch def String generatePseudoCode(Repetition r) 
	'''REPEAT «r.times» TIMES
	BEGIN 
	«FOR e : r.elems»
		«generatePseudoCode(e)»
	«ENDFOR»
	END'''
	
}
