/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.greetings.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.greetings.GreetingsRuntimeModule;
import org.xtext.example.greetings.GreetingsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GreetingsIdeSetup extends GreetingsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GreetingsRuntimeModule(), new GreetingsIdeModule()));
	}
	
}
