/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.greetings.ide;


/**
 * Use this class to register ide components.
 */
public class GreetingsIdeModule extends AbstractGreetingsIdeModule {
}
