/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.hellodsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.hellodsl.helloDsl.Model

@ExtendWith(InjectionExtension)
@InjectWith(HelloDslInjectorProvider)
class HelloDslParsingTest {
	@Inject
	ParseHelper<Model> parseHelper

	@Test
	def void loadModel() {
		val Model result = parseHelper.parse('''
			Hello Xtext!
			Hello Jan!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void parseEmpty() {
		val result = parseHelper.parse('''
		''')
		Assertions.assertNull(result, '''Expecting no Model to be created.''')
	}

	@Test
	def void parseQuestionmark() {
		val result = parseHelper.parse('''
			Hello Xtext?
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertFalse(errors.isEmpty, '''Expecting parse error.''')
	}
}
