/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.turtle.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TurtleUiModule extends AbstractTurtleUiModule {

	public TurtleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
