/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.turtle.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.turtle.turtle.Model

@ExtendWith(InjectionExtension)
@InjectWith(TurtleInjectorProvider)
class TurtleParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void testMove() {
		val result = parseHelper.parse('''
			move forward 4 px
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	@Test
	def void testTurnMove() {
		val result = parseHelper.parse('''
			turn left 90 degrees  
			move forward 4 px
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testRoutine() {
		val result = parseHelper.parse('''
			routine go {
				run go
			}
			run go
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
