/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.turtle.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.turtle.TurtleRuntimeModule;
import org.xtext.example.turtle.TurtleStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TurtleIdeSetup extends TurtleStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TurtleRuntimeModule(), new TurtleIdeModule()));
	}
	
}
