/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.hellodsl.generator;

import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.example.hellodsl.helloDsl.Greeting;
import org.xtext.example.hellodsl.helloDsl.Model;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class HelloDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    fsa.generateFile("pseudoCode.txt", this.generatePseudoCode(IterableExtensions.<EObject>head(resource.getContents())));
  }

  protected String _generatePseudoCode(final Model m) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("BEGIN");
    _builder.newLine();
    {
      EList<Greeting> _greetings = m.getGreetings();
      for(final Greeting g : _greetings) {
        String _generatePseudoCode = this.generatePseudoCode(g);
        _builder.append(_generatePseudoCode);
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("END");
    return _builder.toString();
  }

  protected String _generatePseudoCode(final Greeting g) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("SAY \"Hello ");
    String _subject = g.getSubject();
    _builder.append(_subject);
    _builder.append("!\"");
    return _builder.toString();
  }

  @XbaseGenerated
  public String generatePseudoCode(final EObject g) {
    if (g instanceof Greeting) {
      return _generatePseudoCode((Greeting)g);
    } else if (g instanceof Model) {
      return _generatePseudoCode((Model)g);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(g).toString());
    }
  }
}
